name: bpi-r3-mini
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/openwrt/bpi-r3-mini/**

  workflow_dispatch:
jobs:
  provision:
    runs-on: localhost
    steps:
      - name: Run remote echo command via SSH
        uses: runSshOnRemote
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          command: bash iac/openwrt/bpi-r3-mini/scripts/nginx-allconf.sh
