name: ubuntu-init
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/ansible/loadbalancer-init/**
  workflow_dispatch:

jobs:
  provision:
    runs-on: linux/arm
    steps:
    - name: Deploy init via SSH
      run: |
        cat ${{ secrets.SSPASS }} > /tmp/ss_pass
        scp -rf /tmp/ss_pass root@132.243.252.169:/root/.ss_password
        rm /tmp/ss_pass

        ssh -T root@132.243.252.169 << 'EOF'
        set -e
        apt update
        apt install -y ansible
        echo "ansible installed"
        EOF