name: openwrt-bpi-r3m-nginx
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/openwrt/bpi-r3m/**
  workflow_dispatch:
jobs:
  provision:
    runs-on: linux/arm
    steps:
      - name: Run script
        run: |
          git clone http://192.168.111.1:3000/djsasha777/all.git
          cp -rf all/iac/openwrt/bpi-r3m/nginx/* /etc/nginx/
          cp -r all/iac/openwrt/bpi-r3m/front /etc/
          rm -rf all
          chmod 644 -R /etc/nginx
          chmod 755 /etc/nginx
          service nginx restart
          echo "files copied and nginx restarted."
        shell: bash