name: openwrt-bpi-r3m-certs-renew
on:
  workflow_dispatch:
jobs:
  provision:
    runs-on: linux/arm
    steps:
      - name: Run script
        run: |
          chmod +x -R /var/run/acme
          chmod +x -R /var/run/acme/challenge
          /usr/lib/acme/client/acme.sh --debug --renew --force --home /etc/acme -d spongo.ru
        shell: bash