name: openwrt-bpi-r3m-nginx-r
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/openwrt/bpi-r3m/**
  workflow_dispatch:
jobs:
  provision:
    runs-on: linux/arm
    steps:
      - uses: taiki-e/checkout-action@v1
      - name: Run script
        run: |
          ls /home/gitea
        shell: bash