name: ubuntu-haproxy
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/ansible/loadbalancer-haproxy/**
  workflow_dispatch:

jobs:
  provision:
    runs-on: linux/arm
    steps:
    - name: Deploy haproxy via SSH
      run: |
        git clone http://192.168.111.1:3000/djsasha777/all.git

        ssh-keyscan -H 91.149.218.39 >> ~/.ssh/known_hosts

        ssh -i ~/.ssh/id_rsa \
            -oHostKeyAlgorithms=+ssh-rsa \
            -oUserKnownHostsFile=~/.ssh/known_hosts \
            root@91.149.218.39 "mkdir -p /root/loadbalancer-haproxy"

        scp -i ~/.ssh/id_rsa \
            -oHostKeyAlgorithms=+ssh-rsa \
            -oUserKnownHostsFile=~/.ssh/known_hosts \
            -r all/iac/ansible/loadbalancer-haproxy root@91.149.218.39:/root/

        ssh -i ~/.ssh/id_rsa \
            -oHostKeyAlgorithms=+ssh-rsa \
            -oUserKnownHostsFile=~/.ssh/known_hosts \
            -T root@91.149.218.39 << 'EOF'
        set -e
        cd /root/loadbalancer-haproxy
        ansible-playbook haproxy.yaml
        rm -rf /root/loadbalancer-haproxy
        echo "ansible playbook finished"
        EOF
        rm -rf all