name: ubuntu-haproxy
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/ansible/loadbalancer-haproxy/**
  workflow_dispatch:

jobs:
  provision:
    runs-on: linux/arm
    steps:
    - name: Deploy haproxy via SSH
      run: |
        git clone http://192.168.111.1:3000/djsasha777/all.git

        # --- ФИНАЛЬНОЕ И ВЕРНОЕ РЕШЕНИЕ ---
        # 1. Создаем обычный файл для хранения ключей.
        touch /tmp/known_hosts

        # 2. Указываем Dropbear использовать этот файл.
        export DROPBEAR_KNOWN_HOSTS=/tmp/known_hosts

        # 3. Копируем файлы. Dropbear добавит ключ хоста в /tmp/known_hosts.
        scp -i /root/.ssh/dropbear_rsa -r all/iac/ansible/loadbalancer-haproxy root@91.149.218.39:/root/

        # 4. Выполняем команды на сервере.
        # Ключ уже в файле, соединение пройдет успешно.
        ssh -i /root/.ssh/dropbear_rsa -T root@91.149.218.39 << 'EOF'
        set -e
        cd /root/loadbalancer-haproxy
        ansible-playbook haproxy.yaml
        rm -rf /root/loadbalancer-haproxy
        echo "ansible playbook finished"
        EOF

        rm -rf all