name: openwrt-r3g-nginx
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/openwrt/xiaomi-r3g/**
  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 91.149.218.39
          username: ${{ secrets.R3GUSERNAME }}
          password: ${{ secrets.R3GPASSWORD }}
          port: 4091
          script_path: iac/openwrt/xiaomi-r3g/scripts/nginx-allconf.sh