name: ubuntu-shadowsocks2
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/ansible/test/**
  workflow_dispatch:

jobs:
  provision:
    runs-on: linux/arm
    steps:
    - name: Deploy shadowsocks via SSH
      run: |
        git clone http://192.168.111.1:3000/djsasha777/all.git

        scp -r all/iac/ansible/loadbalancer-shadowsocks root@213.182.204.227:/root/

        cat ${{ secrets.DOCKERHUB_PASSWORD }} > /tmp/ss_pass
        scp -r /tmp/ss_pass root@213.182.204.227:/root/.ss2_password
        rm /tmp/ss_pass
        
        rm -rf all