name: openwrt-bpi-r3m-nginx
on:
  push:
    branches: [ "main" ]
    paths:
      - iac/openwrt/bpi-r3-mini/**
  workflow_dispatch:
jobs:
  provision:
    runs-on: macos-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 192.168.49.2
          username: ${{ secrets.R3GUSERNAME }}
          password: ${{ secrets.R3GPASSWORD }}
          port: 22
          script_path: iac/openwrt/bpi-r3-mini/scripts/nginx-allconf.sh