#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=0

START_ARGS=""

run_runner() {
    procd_open_instance
    procd_set_param command /home/gitea/bin/runner daemon -c /home/gitea/config.yaml
    procd_set_param workdir /home/gitea
    procd_set_param respawn
    procd_set_param respawn_threshold 30
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

boot() {
    run_runner
}

start_service() {
    run_runner
}