#!/bin/sh /etc/rc.common

USE_PROCD=1

START=90
STOP=90

GITEA_USER="gitea"
GITEA_HOME="/home/gitea"
GITEA_BIN="/home/gitea/bin/gitea"
GITEA_CONFIG="/home/gitea/config.ini"

start_service() {
	procd_open_instance
	procd_set_param command "$GITEA_BIN" web --config "$GITEA_CONFIG"
	procd_set_param user "$GITEA_USER"
	procd_set_param env GITEA_WORK_DIR="$GITEA_HOME"
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}

stop_service() {
	:  # procd сам останавливает по PID
}

reload_service() {
	procd_signal_service HUP
}

service_triggers() {
	procd_add_reload_trigger "gitea"
}